### ISSUE TITLE
Access denied Bitbucket link

### ISSUE THREAD

**Issue by nthuat** [3mph4515/localize-maven#1]
I cannot access into https://bitbucket.org/jerminal/localize-android-studio-plugin/src/c3c074cdc7d8?at=master. Pls help me fix it.

**Comment by 3mph4515** [comment]
@thuat26 Sorry for this. Try to download it here 
https://dl.dropboxusercontent.com/u/17996782/Localize.zip

**Comment by nthuat** [comment]
Yeahhh! Thanks a bunch! :+1:
